services:
  - type: web
    name: flask-app
    envVars:
      - key: DATABASE_URL
        value: postgresql://gym_management_e8ka_user:Vg6iFw6R3eM38IrjZzqaH2qjWYFbEeBz@dpg-cv7js9u0jms73e66mrg-a:5432/gym_management_e8ka
